name: Pyanalyze

on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install
        run: |
          python -m pip install -e .
          python -m pip install pyanalyze==0.13.1
      - name: Run
        # TODO check additional directories
        run: PYTHONPATH=. python -m pyanalyze --config-file pyproject.toml taxonomy/
